// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PiggyzenMvp.API.Data;

#nullable disable

namespace PiggyzenMvp.API.Data.Migrations
{
    [DbContext(typeof(PiggyzenMvpContext))]
    [Migration("20251115130245_RemoveAmountRangeFromCategorizationRule")]
    partial class RemoveAmountRangeFromCategorizationRule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("PiggyzenMvp.API.Models.CategorizationRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDescriptionAutoGenerated")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsPositive")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsRefund")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedDescription")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("UsageCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TimesUsed");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("NormalizedDescription");

                    b.HasIndex("NormalizedDescription", "IsPositive");

                    b.ToTable("CategorizationRules");
                });

            modelBuilder.Entity("PiggyzenMvp.API.Models.CategorizationUsage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CategorizationRuleId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TransactionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UsedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("WasOverridden")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategorizationRuleId");

                    b.HasIndex("TransactionId")
                        .IsUnique();

                    b.ToTable("CategorizationUsages");
                });

            modelBuilder.Entity("PiggyzenMvp.API.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSystemCategory")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsSystemCategory = true,
                            Name = "Income"
                        },
                        new
                        {
                            Id = 2,
                            IsSystemCategory = true,
                            Name = "Housing"
                        },
                        new
                        {
                            Id = 3,
                            IsSystemCategory = true,
                            Name = "Vehicle"
                        },
                        new
                        {
                            Id = 4,
                            IsSystemCategory = true,
                            Name = "Fixed Expenses"
                        },
                        new
                        {
                            Id = 5,
                            IsSystemCategory = true,
                            Name = "Variable Expenses"
                        },
                        new
                        {
                            Id = 6,
                            IsSystemCategory = true,
                            Name = "Transfers"
                        });
                });

            modelBuilder.Entity("PiggyzenMvp.API.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Balance")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BookingDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImportId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("PiggyzenMvp.API.Models.CategorizationRule", b =>
                {
                    b.HasOne("PiggyzenMvp.API.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PiggyzenMvp.API.Models.CategorizationUsage", b =>
                {
                    b.HasOne("PiggyzenMvp.API.Models.CategorizationRule", "CategorizationRule")
                        .WithMany("Usages")
                        .HasForeignKey("CategorizationRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PiggyzenMvp.API.Models.Transaction", "Transaction")
                        .WithOne("CategorizationUsage")
                        .HasForeignKey("PiggyzenMvp.API.Models.CategorizationUsage", "TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategorizationRule");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("PiggyzenMvp.API.Models.Category", b =>
                {
                    b.HasOne("PiggyzenMvp.API.Models.Category", "ParentCategory")
                        .WithMany()
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("PiggyzenMvp.API.Models.Transaction", b =>
                {
                    b.HasOne("PiggyzenMvp.API.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PiggyzenMvp.API.Models.CategorizationRule", b =>
                {
                    b.Navigation("Usages");
                });

            modelBuilder.Entity("PiggyzenMvp.API.Models.Transaction", b =>
                {
                    b.Navigation("CategorizationUsage");
                });
#pragma warning restore 612, 618
        }
    }
}
