using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace PiggyzenMvp.API.Data.Migrations
{
    /// <inheritdoc />
    public partial class AddOneToOneUsage : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "CategorizationHistories",
                columns: table => new
                {
                    Id = table.Column<int>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    Description = table.Column<string>(type: "TEXT", maxLength: 512, nullable: false),
                    NormalizedDescription = table.Column<string>(type: "TEXT", maxLength: 256, nullable: false),
                    IsDescriptionAutoGenerated = table.Column<bool>(type: "INTEGER", nullable: false),
                    IsPositive = table.Column<bool>(type: "INTEGER", nullable: true),
                    MinAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    MaxAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    IsRefund = table.Column<bool>(type: "INTEGER", nullable: true),
                    CategoryId = table.Column<int>(type: "INTEGER", nullable: false),
                    Created = table.Column<DateTime>(type: "TEXT", nullable: false),
                    TimesUsed = table.Column<int>(type: "INTEGER", nullable: false),
                    TimesConfirmed = table.Column<int>(type: "INTEGER", nullable: false),
                    TimesOverridden = table.Column<int>(type: "INTEGER", nullable: false),
                    LastUsedAt = table.Column<DateTime>(type: "TEXT", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_CategorizationHistories", x => x.Id);
                    table.ForeignKey(
                        name: "FK_CategorizationHistories_Categories_CategoryId",
                        column: x => x.CategoryId,
                        principalTable: "Categories",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "CategorizationUsages",
                columns: table => new
                {
                    Id = table.Column<int>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    Amount = table.Column<decimal>(type: "decimal(18,2)", nullable: false),
                    TransactionDate = table.Column<DateTime>(type: "TEXT", nullable: false),
                    TransactionId = table.Column<int>(type: "INTEGER", nullable: false),
                    CategorizationHistoryId = table.Column<int>(type: "INTEGER", nullable: false),
                    UsedAt = table.Column<DateTime>(type: "TEXT", nullable: false),
                    WasOverridden = table.Column<DateTime>(type: "TEXT", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_CategorizationUsages", x => x.Id);
                    table.ForeignKey(
                        name: "FK_CategorizationUsages_CategorizationHistories_CategorizationHistoryId",
                        column: x => x.CategorizationHistoryId,
                        principalTable: "CategorizationHistories",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_CategorizationUsages_Transactions_TransactionId",
                        column: x => x.TransactionId,
                        principalTable: "Transactions",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_CategorizationHistories_CategoryId",
                table: "CategorizationHistories",
                column: "CategoryId");

            migrationBuilder.CreateIndex(
                name: "IX_CategorizationHistories_NormalizedDescription",
                table: "CategorizationHistories",
                column: "NormalizedDescription");

            migrationBuilder.CreateIndex(
                name: "IX_CategorizationHistories_NormalizedDescription_IsPositive",
                table: "CategorizationHistories",
                columns: new[] { "NormalizedDescription", "IsPositive" });

            migrationBuilder.CreateIndex(
                name: "IX_CategorizationUsages_CategorizationHistoryId",
                table: "CategorizationUsages",
                column: "CategorizationHistoryId");

            migrationBuilder.CreateIndex(
                name: "IX_CategorizationUsages_TransactionId",
                table: "CategorizationUsages",
                column: "TransactionId",
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "CategorizationUsages");

            migrationBuilder.DropTable(
                name: "CategorizationHistories");
        }
    }
}
