using System.ComponentModel.DataAnnotations.Schema;

namespace PiggyzenMvp.API.Models
{
    public class CategorizationRule
    {
        public int Id { get; set; }

        // Originalbeskrivning (från t.ex. banken)
        public string Description { get; set; } = "";

        // Normaliserad beskrivning, används för matchning
        public string NormalizedDescription { get; set; } = "";

        // Om beskrivningen autogenererats (t.ex. av banken)
        public bool IsDescriptionAutoGenerated { get; set; }

        // Teckenbaserat villkor – används för att skilja köp från återköp, inkomst från utgift
        public bool? IsPositive { get; set; } // true = endast +belopp, false = endast –belopp, null = båda

        // Beloppsintervall (valfritt)
        // Används inte just nu.
        /* 1. MinAmount/MaxAmount ska användas sparsamt (endast när det finns tydliga kluster)

Vi kom fram till att beloppsintervall kan vara värdefullt i vissa specifika fall – men att det är riskabelt att använda dem som primära beslutsregler.

Beloppsintervall är bra när:
    •	Du har ett tydligt, stabilt beloppsmönster
(Circle K tankning: –650 till –900)
    •	Användaren har konsekventa lågbeloppsköp på samma merchant
(Circle K snacks: –15 till –120)
    •	Du har ett unikt kluster som skiljer kategorierna åt
(Släpvagn: –280 till –400)

Beloppsintervall är inte bra när:
    •	Beloppen varierar kraftigt
    •	Merchant är bred (ICA, Coop, Amazon, Biltema…)
    •	Fler kategorier delar samma beloppsnivå
    •	Det finns risk för “falska kluster” */
        // public decimal? MinAmount { get; set; }
        // public decimal? MaxAmount { get; set; }

        // Om CH är baserad på återbetalning
        // Att göra - skapa service för att upptäcka återbetalningar automatiskt
        public bool? IsRefund { get; set; }

        // Kategorin som transaktioner matchade mot denna regel tillhör
        public int CategoryId { get; set; }
        public Category? Category { get; set; }

        // Skapatidpunkt
        public DateTime Created { get; set; } = DateTime.UtcNow;

        // Statistik (kan uppdateras efter varje matchning)
        [Column("TimesUsed")]
        public int UsageCount { get; set; } = 0;
        public DateTime? LastUsedAt { get; set; }

        // Navigering till kopplingar (CategorizationUsage)
        public ICollection<CategorizationUsage> Usages { get; set; } =
            new List<CategorizationUsage>();
    }

    public class CategorizationUsage
    {
        public int Id { get; set; }
        public decimal Amount { get; set; }

        public required DateTime TransactionDate { get; set; }
        public int TransactionId { get; set; }
        public Transaction Transaction { get; set; } = null!;

        public int CategorizationRuleId { get; set; }
        public CategorizationRule CategorizationRule { get; set; } = null!;

        public DateTime UsedAt { get; set; } = DateTime.UtcNow;

        // Möjlighet till omkoppling:
        public DateTime? WasOverridden { get; set; }
        public CategorizationSource? Source { get; set; }
    }

    public enum CategorizationSource
    {
        Auto = 0,
        Manual = 1,
        AI = 2,
    }
}
