namespace PiggyzenMvp.API.Models
{
    // Kanske byta namn till CategorizationRule eller liknande?
    public class CategorizationHistory
    {
        public int Id { get; set; }

        // Originalbeskrivning (från t.ex. banken)
        public string Description { get; set; } = "";

        // Normaliserad beskrivning, används för matchning
        public string NormalizedDescription { get; set; } = "";

        // Om beskrivningen autogenererats (t.ex. av banken)
        public bool IsDescriptionAutoGenerated { get; set; }

        // Teckenbaserat villkor – används för att skilja köp från återköp, inkomst från utgift
        public bool? IsPositive { get; set; } // true = endast +belopp, false = endast –belopp, null = båda

        // Beloppsintervall (valfritt)
        public decimal? MinAmount { get; set; }
        public decimal? MaxAmount { get; set; }

        // Om CH är baserad på återbetalning
        public bool? IsRefund { get; set; }

        // Kategorin som transaktioner matchade mot denna regel tillhör
        public int CategoryId { get; set; }
        public Category? Category { get; set; }

        // Skapatidpunkt
        public DateTime Created { get; set; } = DateTime.UtcNow;

        // Statistik (kan uppdateras efter varje matchning)
        public int TimesUsed { get; set; } = 0;
        public DateTime? LastUsedAt { get; set; }

        // Navigering till kopplingar (CategorizationUsage)
        public ICollection<CategorizationUsage> Usages { get; set; } =
            new List<CategorizationUsage>();
    }

    public class CategorizationUsage
    {
        public int Id { get; set; }
        public decimal Amount { get; set; }

        public required DateTime TransactionDate { get; set; }
        public int TransactionId { get; set; }
        public Transaction Transaction { get; set; } = null!;

        public int CategorizationHistoryId { get; set; }
        public CategorizationHistory CategorizationHistory { get; set; } = null!;

        public DateTime UsedAt { get; set; } = DateTime.UtcNow;

        // Möjlighet till omkoppling:
        public DateTime? WasOverridden { get; set; }
    }
}
