using System.Reflection;
using PiggyzenMvp.API.Services;
using Xunit;

namespace PiggyzenMvp.Tests;

public class CategorizationServiceTests
{
    private static bool InvokeIsDescriptionAutoGenerated(string input)
    {
        var mi = typeof(CategorizationService).GetMethod(
            "IsDescriptionAutoGenerated",
            BindingFlags.NonPublic | BindingFlags.Static
        );
        Assert.NotNull(mi);
        return (bool)mi!.Invoke(null, new object?[] { input })!;
    }

    [Theory]
    [InlineData(null, false)]
    [InlineData("", false)]
    [InlineData("ICA", false)]
    [InlineData("ICA KVANTUM", true)] // All caps + minst två ord
    [InlineData("VISA,12", true)] // ",XX" där XX är två siffror
    [InlineData("VISA,1", false)]
    [InlineData("VISA,123", false)]
    [InlineData("STATOIL AB", true)] // Innehåller " AB"
    [InlineData("Company Ab", false)] // Litet ab ska inte matcha
    public void IsDescriptionAutoGenerated_Rules(string? input, bool expected)
    {
        var actual = InvokeIsDescriptionAutoGenerated(input!);
        Assert.Equal(expected, actual);
    }
}
